const mongoose = require("mongoose");
require("dotenv").config();

console.log("🤖 Creating AI Players...");

const UserSchema = new mongoose.Schema(
  {
    username: { type: String, required: false }, // Tidak required untuk AI
    email: { type: String, required: false }, // Tidak required untuk AI
    password: { type: String, required: false }, // Tidak required untuk AI
    role: { type: String, required: true },
    profilePicture: String,
    bio: String,
    playerInfo: {
      firstName: String,
      lastName: String,
      position: String,
      age: Number,
      height: Number,
      weight: Number,
      nationality: String,
      club: String,
      offensiveAwareness: Number,
      dribbling: Number,
      lowPass: Number,
      finishing: Number,
      placeKicking: Number,
      speed: Number,
      kickingPower: Number,
      physicalContact: Number,
      stamina: Number,
      ballWinning: Number,
      ballControl: Number,
      tightPossession: Number,
      loftedPass: Number,
      heading: Number,
      curl: Number,
      acceleration: Number,
      jump: Number,
      balance: Number,
      defensiveAwareness: Number,
      aggression: Number,
      gkAwareness: Number,
      gkClearing: Number,
      gkReach: Number,
      gkCatching: Number,
      gkReflexes: Number,
      weakFootUsage: Number,
      weakFootAcc: Number,
      form: Number,
      injuryResistance: Number,
      style: String,
    },
    managerInfo: {
      clubName: String,
      budget: Number,
      reputation: Number,
      experience: Number,
      level: Number,
    },
    coins: { type: Number, default: 1000 },
    energy: { type: Number, default: 100 },
    stats: {
      matchesPlayed: { type: Number, default: 0 },
      matchesWon: { type: Number, default: 0 },
      goals: { type: Number, default: 0 },
      assists: { type: Number, default: 0 },
      cleanSheets: { type: Number, default: 0 },
      yellowCards: { type: Number, default: 0 },
      redCards: { type: Number, default: 0 },
      tournamentsWon: { type: Number, default: 0 },
      skillPoints: { type: Number, default: 0 },
      totalEarnings: { type: Number, default: 0 },
    },
    isActive: { type: Boolean, default: true },
    isAI: { type: Boolean, default: false }, // Flag untuk menandai AI players
  },
  { timestamps: true }
);

const User = mongoose.model("User", UserSchema);

// AI Players data yang sama seperti di frontend
const aiPlayersData = [
  {
    username: "ElitronicMessi", // Username unik untuk AI
    email: "messi.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "🤖",
    bio: "AI yang terinspirasi dari kemampuan dribbling dan passing yang luar biasa. Master dalam menciptakan peluang dari ruang sempit.",
    isAI: true,
    playerInfo: {
      firstName: "Leo",
      lastName: "AI-10",
      position: "RW",
      age: 28,
      height: 170,
      weight: 72,
      nationality: "Argentina",
      club: "AI Barcelona",
      // Elite winger/playmaker skills
      offensiveAwareness: 99,
      dribbling: 99,
      lowPass: 95,
      finishing: 92,
      placeKicking: 95,
      speed: 85,
      kickingPower: 88,
      physicalContact: 68,
      stamina: 85,
      ballWinning: 45,
      ballControl: 99,
      tightPossession: 99,
      loftedPass: 90,
      heading: 70,
      curl: 95,
      acceleration: 92,
      jump: 68,
      balance: 95,
      defensiveAwareness: 35,
      aggression: 45,
      gkAwareness: 20,
      gkClearing: 20,
      gkReach: 20,
      gkCatching: 20,
      gkReflexes: 20,
      weakFootUsage: 4,
      weakFootAcc: 4,
      form: 8,
      injuryResistance: 2,
      style: "technical",
    },
    energy: 95,
    coins: 15000,
    stats: {
      matchesPlayed: 120,
      matchesWon: 89,
      goals: 78,
      assists: 65,
      cleanSheets: 0,
      yellowCards: 12,
      redCards: 1,
      tournamentsWon: 8,
      skillPoints: 2850,
      totalEarnings: 180000,
    },
  },
  {
    username: "CyberRonaldo", // Username unik untuk AI
    email: "ronaldo.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "⚡",
    bio: "AI striker dengan kemampuan finishing yang menakjubkan. Tidak pernah menyia-nyiakan peluang di kotak penalti.",
    isAI: true,
    playerInfo: {
      firstName: "Cristiano",
      lastName: "AI-7",
      position: "ST",
      age: 30,
      height: 187,
      weight: 84,
      nationality: "Portugal",
      club: "AI United",
      // Elite striker skills
      offensiveAwareness: 98,
      dribbling: 88,
      lowPass: 82,
      finishing: 99,
      placeKicking: 95,
      speed: 90,
      kickingPower: 98,
      physicalContact: 95,
      stamina: 92,
      ballWinning: 35,
      ballControl: 88,
      tightPossession: 85,
      loftedPass: 78,
      heading: 99,
      curl: 88,
      acceleration: 95,
      jump: 99,
      balance: 88,
      defensiveAwareness: 30,
      aggression: 88,
      gkAwareness: 15,
      gkClearing: 15,
      gkReach: 15,
      gkCatching: 15,
      gkReflexes: 15,
      weakFootUsage: 4,
      weakFootAcc: 4,
      form: 8,
      injuryResistance: 3,
      style: "attacking",
    },
    energy: 98,
    coins: 18500,
    stats: {
      matchesPlayed: 115,
      matchesWon: 85,
      goals: 92,
      assists: 28,
      cleanSheets: 0,
      yellowCards: 8,
      redCards: 0,
      tournamentsWon: 7,
      skillPoints: 3100,
      totalEarnings: 220000,
    },
  },
  {
    username: "VirtualVirgilAI", // Username unik untuk AI
    email: "virgil.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "🛡️",
    bio: "AI defender yang tidak tertembus. Kemampuan membaca permainan dan antisipasi yang luar biasa.",
    isAI: true,
    playerInfo: {
      firstName: "Virgil",
      lastName: "AI-4",
      position: "CB",
      age: 29,
      height: 193,
      weight: 92,
      nationality: "Netherlands",
      club: "AI Liverpool",
      // Elite centre back skills
      offensiveAwareness: 25,
      dribbling: 70,
      lowPass: 90,
      finishing: 45,
      placeKicking: 85,
      speed: 78,
      kickingPower: 88,
      physicalContact: 98,
      stamina: 92,
      ballWinning: 98,
      ballControl: 85,
      tightPossession: 80,
      loftedPass: 95,
      heading: 99,
      curl: 75,
      acceleration: 75,
      jump: 99,
      balance: 92,
      defensiveAwareness: 99,
      aggression: 85,
      gkAwareness: 20,
      gkClearing: 20,
      gkReach: 20,
      gkCatching: 20,
      gkReflexes: 20,
      weakFootUsage: 3,
      weakFootAcc: 3,
      form: 7,
      injuryResistance: 3,
      style: "defensive",
    },
    energy: 92,
    coins: 12000,
    stats: {
      matchesPlayed: 98,
      matchesWon: 74,
      goals: 12,
      assists: 8,
      cleanSheets: 56,
      yellowCards: 15,
      redCards: 2,
      tournamentsWon: 5,
      skillPoints: 2600,
      totalEarnings: 150000,
    },
  },
  {
    username: "KDBotAI", // Username unik untuk AI
    email: "kdb.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "🎯",
    bio: "AI midfielder dengan vision yang luar biasa. Mampu mengoper bola dengan presisi tinggi dari jarak jauh.",
    isAI: true,
    playerInfo: {
      firstName: "Kevin",
      lastName: "AI-17",
      position: "CM",
      age: 27,
      height: 181,
      weight: 76,
      nationality: "Belgium",
      club: "AI City",
      // Elite central midfielder skills
      offensiveAwareness: 92,
      dribbling: 88,
      lowPass: 99,
      finishing: 88,
      placeKicking: 95,
      speed: 75,
      kickingPower: 95,
      physicalContact: 78,
      stamina: 88,
      ballWinning: 70,
      ballControl: 92,
      tightPossession: 90,
      loftedPass: 99,
      heading: 75,
      curl: 98,
      acceleration: 78,
      jump: 72,
      balance: 88,
      defensiveAwareness: 75,
      aggression: 65,
      gkAwareness: 18,
      gkClearing: 18,
      gkReach: 18,
      gkCatching: 18,
      gkReflexes: 18,
      weakFootUsage: 4,
      weakFootAcc: 4,
      form: 8,
      injuryResistance: 2,
      style: "technical",
    },
    energy: 88,
    coins: 14000,
    stats: {
      matchesPlayed: 105,
      matchesWon: 78,
      goals: 35,
      assists: 72,
      cleanSheets: 12,
      yellowCards: 18,
      redCards: 1,
      tournamentsWon: 6,
      skillPoints: 2900,
      totalEarnings: 175000,
    },
  },
  {
    username: "NeymarAI_Jr", // Username unik untuk AI
    email: "neymar.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "🌟",
    bio: "AI winger dengan kemampuan skill yang memukau. Sulit ditebak dan selalu menghibur penonton.",
    isAI: true,
    playerInfo: {
      firstName: "Neymar",
      lastName: "AI-10",
      position: "LW",
      age: 26,
      height: 175,
      weight: 68,
      nationality: "Brazil",
      club: "AI PSG",
      // Elite skillful winger
      offensiveAwareness: 92,
      dribbling: 98,
      lowPass: 88,
      finishing: 88,
      placeKicking: 90,
      speed: 92,
      kickingPower: 85,
      physicalContact: 65,
      stamina: 82,
      ballWinning: 35,
      ballControl: 98,
      tightPossession: 95,
      loftedPass: 85,
      heading: 65,
      curl: 92,
      acceleration: 95,
      jump: 70,
      balance: 98,
      defensiveAwareness: 30,
      aggression: 75,
      gkAwareness: 15,
      gkClearing: 15,
      gkReach: 15,
      gkCatching: 15,
      gkReflexes: 15,
      weakFootUsage: 4,
      weakFootAcc: 3,
      form: 7,
      injuryResistance: 1,
      style: "technical",
    },
    energy: 85,
    coins: 13500,
    stats: {
      matchesPlayed: 95,
      matchesWon: 68,
      goals: 58,
      assists: 45,
      cleanSheets: 0,
      yellowCards: 22,
      redCards: 3,
      tournamentsWon: 4,
      skillPoints: 2400,
      totalEarnings: 160000,
    },
  },
  {
    username: "HaalandBot9", // Username unik untuk AI
    email: "haaland.ai@football.com", // Email unik untuk AI
    role: "player",
    profilePicture: "🦾",
    bio: "AI striker muda dengan kekuatan fisik yang luar biasa. Goal machine yang sangat efisien di depan gawang.",
    isAI: true,
    playerInfo: {
      firstName: "Erling",
      lastName: "AI-9",
      position: "ST",
      age: 24,
      height: 194,
      weight: 88,
      nationality: "Norway",
      club: "AI City",
      // Elite physical striker
      offensiveAwareness: 95,
      dribbling: 78,
      lowPass: 70,
      finishing: 98,
      placeKicking: 85,
      speed: 88,
      kickingPower: 98,
      physicalContact: 98,
      stamina: 95,
      ballWinning: 30,
      ballControl: 82,
      tightPossession: 75,
      loftedPass: 65,
      heading: 95,
      curl: 75,
      acceleration: 92,
      jump: 98,
      balance: 85,
      defensiveAwareness: 25,
      aggression: 92,
      gkAwareness: 12,
      gkClearing: 12,
      gkReach: 12,
      gkCatching: 12,
      gkReflexes: 12,
      weakFootUsage: 3,
      weakFootAcc: 3,
      form: 8,
      injuryResistance: 3,
      style: "attacking",
    },
    energy: 94,
    coins: 16000,
    stats: {
      matchesPlayed: 85,
      matchesWon: 68,
      goals: 89,
      assists: 15,
      cleanSheets: 0,
      yellowCards: 5,
      redCards: 0,
      tournamentsWon: 6,
      skillPoints: 2800,
      totalEarnings: 195000,
    },
  },
];

const main = async () => {
  try {
    console.log("📡 Connecting to MongoDB...");
    await mongoose.connect(
      process.env.MONGODB_URI || "mongodb://localhost:27017/pesdb"
    );
    console.log("✅ Connected to MongoDB");

    // Hapus AI players yang sudah ada (jika ada)
    console.log("🗑️ Removing existing AI players...");
    await User.deleteMany({
      $or: [
        { isAI: true },
        {
          username: {
            $in: [
              "ElitronicMessi",
              "CyberRonaldo",
              "VirtualVirgilAI",
              "KDBotAI",
              "NeymarAI_Jr",
              "HaalandBot9",
            ],
          },
        },
      ],
    });

    console.log("🤖 Creating AI players...");

    for (const playerData of aiPlayersData) {
      const aiPlayer = new User(playerData);
      await aiPlayer.save();
      console.log(
        `✅ Created AI player: ${playerData.playerInfo.firstName} ${playerData.playerInfo.lastName}`
      );
    }

    console.log(`🎉 Successfully created ${aiPlayersData.length} AI players!`);
  } catch (error) {
    console.error("❌ Error creating AI players:", error);
  } finally {
    await mongoose.disconnect();
    console.log("👋 Disconnected from MongoDB");
    process.exit(0);
  }
};

main();
