import mongoose from "mongoose";
import { SkillTemplate } from "../models/SkillTemplate";
import dotenv from "dotenv";

dotenv.config();

const skillTemplates = [
  // Player Skills (gabungan basic & special, type: 'playerSkill')
  {
    skillId: "scissorsFeint",
    skillName: "Scissors Feint",
    skillType: "playerSkill",
    description: "Skill pemain: Scissors Feint",
    longDescription: "Skill pemain: Scissors Feint.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "doubleTouch",
    skillName: "Double Touch",
    skillType: "playerSkill",
    description: "Skill pemain: Double Touch",
    longDescription: "Skill pemain: Double Touch.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "flipFlap",
    skillName: "Flip Flap",
    skillType: "playerSkill",
    description: "Skill pemain: Flip Flap",
    longDescription: "Skill pemain: Flip Flap.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "marseilleTurn",
    skillName: "Marseille Turn",
    skillType: "playerSkill",
    description: "Skill pemain: Marseille Turn",
    longDescription: "Skill pemain: Marseille Turn.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "sombrero",
    skillName: "Sombrero",
    skillType: "playerSkill",
    description: "Skill pemain: Sombrero",
    longDescription: "Skill pemain: Sombrero.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "crossOverTurn",
    skillName: "Cross Over Turn",
    skillType: "playerSkill",
    description: "Skill pemain: Cross Over Turn",
    longDescription: "Skill pemain: Cross Over Turn.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "cutBehindTurn",
    skillName: "Cut Behind & Turn",
    skillType: "playerSkill",
    description: "Skill pemain: Cut Behind & Turn",
    longDescription: "Skill pemain: Cut Behind & Turn.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "scotchMove",
    skillName: "Scotch Move",
    skillType: "playerSkill",
    description: "Skill pemain: Scotch Move",
    longDescription: "Skill pemain: Scotch Move.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "stepOnSkillControl",
    skillName: "Step On Skill control",
    skillType: "playerSkill",
    description: "Skill pemain: Step On Skill control",
    longDescription: "Skill pemain: Step On Skill control.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "heading",
    skillName: "Heading",
    skillType: "playerSkill",
    description: "Skill pemain: Heading",
    longDescription: "Skill pemain: Heading.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "longRangeDrive",
    skillName: "Long Range Drive",
    skillType: "playerSkill",
    description: "Skill pemain: Long Range Drive",
    longDescription: "Skill pemain: Long Range Drive.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "chipShotControl",
    skillName: "Chip Shot Control",
    skillType: "playerSkill",
    description: "Skill pemain: Chip Shot Control",
    longDescription: "Skill pemain: Chip Shot Control.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "longRangeShooting",
    skillName: "Long Range Shooting",
    skillType: "playerSkill",
    description: "Skill pemain: Long Range Shooting",
    longDescription: "Skill pemain: Long Range Shooting.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "knuckleShot",
    skillName: "Knuckle Shot",
    skillType: "playerSkill",
    description: "Skill pemain: Knuckle Shot",
    longDescription: "Skill pemain: Knuckle Shot.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "dippingShot",
    skillName: "Dipping Shot",
    skillType: "playerSkill",
    description: "Skill pemain: Dipping Shot",
    longDescription: "Skill pemain: Dipping Shot.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "risingShots",
    skillName: "Rising Shots",
    skillType: "playerSkill",
    description: "Skill pemain: Rising Shots",
    longDescription: "Skill pemain: Rising Shots.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "acrobaticFinishing",
    skillName: "Acrobatic Finishing",
    skillType: "playerSkill",
    description: "Skill pemain: Acrobatic Finishing",
    longDescription: "Skill pemain: Acrobatic Finishing.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "heelTrick",
    skillName: "Heel Trick",
    skillType: "playerSkill",
    description: "Skill pemain: Heel Trick",
    longDescription: "Skill pemain: Heel Trick.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "firstTimeShot",
    skillName: "First-time Shot",
    skillType: "playerSkill",
    description: "Skill pemain: First-time Shot",
    longDescription: "Skill pemain: First-time Shot.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "oneTouchPass",
    skillName: "One-touch Pass",
    skillType: "playerSkill",
    description: "Skill pemain: One-touch Pass",
    longDescription: "Skill pemain: One-touch Pass.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "throughPassing",
    skillName: "Through Passing",
    skillType: "playerSkill",
    description: "Skill pemain: Through Passing",
    longDescription: "Skill pemain: Through Passing.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "weightedPass",
    skillName: "Weighted Pass",
    skillType: "playerSkill",
    description: "Skill pemain: Weighted Pass",
    longDescription: "Skill pemain: Weighted Pass.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "pinpointCrossing",
    skillName: "Pinpoint Crossing",
    skillType: "playerSkill",
    description: "Skill pemain: Pinpoint Crossing",
    longDescription: "Skill pemain: Pinpoint Crossing.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "outsideCurler",
    skillName: "Outside Curler",
    skillType: "playerSkill",
    description: "Skill pemain: Outside Curler",
    longDescription: "Skill pemain: Outside Curler.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "rabona",
    skillName: "Rabona",
    skillType: "playerSkill",
    description: "Skill pemain: Rabona",
    longDescription: "Skill pemain: Rabona.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "noLookPass",
    skillName: "No Look Pass",
    skillType: "playerSkill",
    description: "Skill pemain: No Look Pass",
    longDescription: "Skill pemain: No Look Pass.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "lowLoftedPass",
    skillName: "Low Lofted Pass",
    skillType: "playerSkill",
    description: "Skill pemain: Low Lofted Pass",
    longDescription: "Skill pemain: Low Lofted Pass.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "gkLowPunt",
    skillName: "GK Low Punt",
    skillType: "playerSkill",
    description: "Skill pemain: GK Low Punt",
    longDescription: "Skill pemain: GK Low Punt.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "gkHighPunt",
    skillName: "GK High Punt",
    skillType: "playerSkill",
    description: "Skill pemain: GK High Punt",
    longDescription: "Skill pemain: GK High Punt.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "longThrow",
    skillName: "Long Throw",
    skillType: "playerSkill",
    description: "Skill pemain: Long Throw",
    longDescription: "Skill pemain: Long Throw.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "gkLongThrow",
    skillName: "GK Long Throw",
    skillType: "playerSkill",
    description: "Skill pemain: GK Long Throw",
    longDescription: "Skill pemain: GK Long Throw.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "penaltySpecialist",
    skillName: "Penalty Specialist",
    skillType: "playerSkill",
    description: "Skill pemain: Penalty Specialist",
    longDescription: "Skill pemain: Penalty Specialist.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "gkPenaltySaver",
    skillName: "GK Penalty Saver",
    skillType: "playerSkill",
    description: "Skill pemain: GK Penalty Saver",
    longDescription: "Skill pemain: GK Penalty Saver.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "gamesmanship",
    skillName: "Gamesmanship",
    skillType: "playerSkill",
    description: "Skill pemain: Gamesmanship",
    longDescription: "Skill pemain: Gamesmanship.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "manMarking",
    skillName: "Man Marking",
    skillType: "playerSkill",
    description: "Skill pemain: Man Marking",
    longDescription: "Skill pemain: Man Marking.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "trackBack",
    skillName: "Track Back",
    skillType: "playerSkill",
    description: "Skill pemain: Track Back",
    longDescription: "Skill pemain: Track Back.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "interception",
    skillName: "Interception",
    skillType: "playerSkill",
    description: "Skill pemain: Interception",
    longDescription: "Skill pemain: Interception.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "acrobaticClear",
    skillName: "Acrobatic Clear",
    skillType: "playerSkill",
    description: "Skill pemain: Acrobatic Clear",
    longDescription: "Skill pemain: Acrobatic Clear.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "captaincy",
    skillName: "Captaincy",
    skillType: "playerSkill",
    description: "Skill pemain: Captaincy",
    longDescription: "Skill pemain: Captaincy.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "superSub",
    skillName: "Super-sub",
    skillType: "playerSkill",
    description: "Skill pemain: Super-sub",
    longDescription: "Skill pemain: Super-sub.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },
  {
    skillId: "fightingSpirit",
    skillName: "Fighting Spirit",
    skillType: "playerSkill",
    description: "Skill pemain: Fighting Spirit",
    longDescription: "Skill pemain: Fighting Spirit.",
    cost: 0,
    currency: "skillPoints",
    isActive: true,
  },

  // COM Playing Styles (type: 'style')
  {
    skillId: "trickster",
    skillName: "Trickster",
    skillType: "style",
    description: "COM Playing Style: Trickster",
    longDescription: "COM Playing Style: Trickster.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "mazingRun",
    skillName: "Mazing Run",
    skillType: "style",
    description: "COM Playing Style: Mazing Run",
    longDescription: "COM Playing Style: Mazing Run.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "speedingBullet",
    skillName: "Speeding Bullet",
    skillType: "style",
    description: "COM Playing Style: Speeding Bullet",
    longDescription: "COM Playing Style: Speeding Bullet.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "incisiveRun",
    skillName: "Incisive Run",
    skillType: "style",
    description: "COM Playing Style: Incisive Run",
    longDescription: "COM Playing Style: Incisive Run.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "longBallExpert",
    skillName: "Long Ball Expert",
    skillType: "style",
    description: "COM Playing Style: Long Ball Expert",
    longDescription: "COM Playing Style: Long Ball Expert.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "earlyCross",
    skillName: "Early Cross",
    skillType: "style",
    description: "COM Playing Style: Early Cross",
    longDescription: "COM Playing Style: Early Cross.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
  {
    skillId: "longRanger",
    skillName: "Long Ranger",
    skillType: "style",
    description: "COM Playing Style: Long Ranger",
    longDescription: "COM Playing Style: Long Ranger.",
    cost: 0,
    currency: "stylePoints",
    isActive: true,
  },
];

const seedSkills = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(
      process.env.MONGODB_URI ||
        "mongodb://localhost:27017/pes-football-management"
    );

    console.log("🌱 Seeding skill templates...");

    // Clear existing skill templates
    await SkillTemplate.deleteMany({});

    // Insert skill templates
    await SkillTemplate.insertMany(skillTemplates);

    console.log(
      `✅ Successfully seeded ${skillTemplates.length} skill templates`
    );

    // Disconnect from MongoDB
    await mongoose.disconnect();
    console.log("📡 Disconnected from MongoDB");
  } catch (error) {
    console.error("❌ Error seeding skill templates:", error);
    process.exit(1);
  }
};

// Run the seeder
seedSkills();
